### ISSUE TITLE
`set block(breakable: false)` twice

### ISSUE THREAD

**Issue by memeplex** [glambrechts/slydst#2]
https://github.com/glambrechts/slydst/blob/9704ef9190842536866688ed4db314299a6a47cf/slydst.typ#L125C1-L127C1

```
  show stack: set block(breakable: false)
  show stack: set block(breakable: false, above: 0.8em, below: 0.5em)
```

Isn't the first line redundant?

PS: very nice minimalist package.

**Comment by glambrechts** [comment]
Hi, sorry for my late reply! Thank you for having spotted that. I'll remove the first line ;-)
