### ISSUE TITLE
How to change the colour of the theorems?

### ISSUE THREAD

**Issue by kelvin-273** [glambrechts/slydst#3]
Is it possible to change the colour of the frames for theorems and definitions from light blue to something else?
How would one do it?

**Comment by glambrechts** [comment]
Good question. I know I should allow for more customisation (such as the frame colour, but alos the title page, etc). I will try to do something and release it soon.

**Comment by glambrechts** [comment]
For now, I will go for the somewhat dirty solution of adding parameters to all my custom elements, allowing to overwrite (part of) their style.

For later, from what I read, the clean way of doing it would be to define show-set rules for these custom elements (theorems, definitions) such that the user would be able to do something like `show theorem: set frame(color: red)` or even `set frame(color: red)`. Unfortunately, this feature is not available yet (see https://github.com/typst/typst/issues/147).

**Comment by glambrechts** [comment]
I just released Typst 0.1.3. It should be good now (to customise titles and components) with the following code, for example.
```typst
#import "@preview/slydst:0.1.3": *

#show: slides.with(
  ratio: 16/9,
)

#title-slide[
  #text(2em)[*My Custom Title*]
]

== My Red Theorem

#theorem(title: "An interesting theorem", fill-header: red.lighten(65%), radius: 0.2em)[
  Let $p(x, y)$ a probability distribution, we have,
  $
    p(x, y) &= p(x) p(y | x).
  $
]
```

See [README](https://github.com/glambrechts/slydst) for help on the new arguments.

**Comment by glambrechts** [comment]
There is also a template now, so you can create slides from the app by just clicking on "start from template" and then look for Slydst. If you use the command line, it is just `typst init @preview/slydst`.

**Comment by kelvin-273** [comment]
Based on the README, It looks beautiful. Cheers.
